const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let cacheRun=1;
function fmt(n){return Number(n).toLocaleString()}
function seeded(seed){let x=seed>>>0;return()=>((x=(x*1664525+1013904223)>>>0)/4294967296)}
function drawBars(canvas,items,max){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,dpr=window.devicePixelRatio||1;ctx.clearRect(0,0,w,h);ctx.fillStyle='#090e14';ctx.fillRect(0,0,w,h);const pad=52,base=h-42,chartH=h-70,gap=28,bw=(w-pad*2-gap*(items.length-1))/items.length;ctx.strokeStyle='#1f2a37';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=base-chartH*i/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()}items.forEach((it,i)=>{const bh=Math.max(4,chartH*(it.value/max));const x=pad+i*(bw+gap),y=base-bh;const g=ctx.createLinearGradient(0,y,0,base);g.addColorStop(0,it.color);g.addColorStop(1,'rgba(20,28,38,.25)');ctx.fillStyle=g;ctx.fillRect(x,y,bw,bh);ctx.fillStyle='#d7e1ec';ctx.font='700 16px ui-monospace';ctx.textAlign='center';ctx.fillText(it.label,x+bw/2,base+25);ctx.fillStyle=it.color;ctx.font='700 18px ui-monospace';ctx.fillText(it.display??String(it.value),x+bw/2,y-10)});}
function drawLine(canvas,points,label){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#090e14';ctx.fillRect(0,0,w,h);const p=55,base=h-42,chartH=h-78,max=Math.max(...points.map(x=>x.y))*1.1;ctx.strokeStyle='#1f2a37';for(let i=0;i<5;i++){const y=base-chartH*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}const coords=points.map((pt,i)=>({x:p+i*(w-p*2)/(points.length-1||1),y:base-chartH*pt.y/max,...pt}));ctx.strokeStyle='#9ef01a';ctx.lineWidth=3;ctx.beginPath();coords.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.stroke();coords.forEach(q=>{ctx.fillStyle='#9ef01a';ctx.beginPath();ctx.arc(q.x,q.y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b8c5d4';ctx.font='700 13px ui-monospace';ctx.textAlign='center';ctx.fillText(q.xLabel,q.x,base+24);ctx.fillStyle='#9ef01a';ctx.fillText(q.y.toFixed(2)+'×',q.x,q.y-12)});ctx.fillStyle='#748396';ctx.font='700 11px ui-monospace';ctx.textAlign='left';ctx.fillText(label,p,22)}
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab+'Pane').classList.add('active')}));
function bindRange(id,out,suffix=''){const el=$(id),o=$(out),set=()=>o.textContent=fmt(el.value)+suffix;el.addEventListener('input',set);set()}
bindRange('#cacheSize','#cacheSizeOut',' KB');bindRange('#accesses','#accessesOut');bindRange('#instructions','#instOut');bindRange('#branchFreq','#branchOut','%');bindRange('#depPressure','#depOut','%');bindRange('#parallelFraction','#parallelOut','%');
function simulateCache(){const kb=+$cacheSize.value,block=+$blockSize.value,ways=+$ways.value,count=+$accesses.value,pattern=$pattern.value,lines=Math.max(1,Math.floor(kb*1024/block)),sets=Math.max(1,Math.floor(lines/ways));const state=Array.from({length:sets},()=>[]),rng=seeded(kb*17+block*13+ways*7+count);let hits=0,misses=0,evictions=0,addr=0;for(let i=0;i<count;i++){if(pattern==='sequential')addr=i*16;else if(pattern==='random')addr=Math.floor(rng()*1024*1024);else{if(rng()<.78)addr=(Math.floor(i/4)%2048)*16+Math.floor(rng()*4)*16;else addr=Math.floor(rng()*1024*1024)}const line=Math.floor(addr/block),set=line%sets,tag=Math.floor(line/sets),bucket=state[set],idx=bucket.indexOf(tag);if(idx>=0){hits++;bucket.splice(idx,1);bucket.unshift(tag)}else{misses++;if(bucket.length>=ways){bucket.pop();evictions++}bucket.unshift(tag)}}return{hits,misses,evictions,hitRate:hits/count,missRate:misses/count,sets,lines}}
const $cacheSize=$('#cacheSize'),$blockSize=$('#blockSize'),$ways=$('#ways'),$accesses=$('#accesses'),$pattern=$('#pattern');
function runCache(){const r=simulateCache();$('#hitRate').textContent=(r.hitRate*100).toFixed(2)+'%';$('#missRate').textContent=(r.missRate*100).toFixed(2)+'%';$('#hits').textContent=fmt(r.hits);$('#misses').textContent=fmt(r.misses);$('#cacheRunId').textContent='RUN #'+String(cacheRun++).padStart(3,'0');$('#heroHit').textContent=(r.hitRate*100).toFixed(1)+'%';drawBars($('#cacheChart'),[{label:'HITS',value:r.hits,display:fmt(r.hits),color:'#9ef01a'},{label:'MISSES',value:r.misses,display:fmt(r.misses),color:'#ff5d73'},{label:'EVICTIONS',value:r.evictions,display:fmt(r.evictions),color:'#00e5ff'}],Math.max(r.hits,r.misses,r.evictions,1));$('#cacheTerminal').textContent=`$ archpulse cache --cache-size ${$cacheSize.value*1024} --block-size ${$blockSize.value} --ways ${$ways.value} --pattern ${$pattern.value}\nsets=${r.sets} lines=${r.lines} accesses=${fmt(+$accesses.value)} hits=${fmt(r.hits)} misses=${fmt(r.misses)} evictions=${fmt(r.evictions)}\nhit_rate=${(r.hitRate*100).toFixed(2)}% miss_rate=${(r.missRate*100).toFixed(2)}%`}
$('#runCache').addEventListener('click',runCache);
function simulatePipeline(){const n=+$('#instructions').value,bf=+$('#branchFreq').value/100,dep=+$('#depPressure').value/100,p=$('#predictor').value;const predAcc={taken:.68,not:.62,'1bit':.82,'2bit':.91}[p];const branches=Math.round(n*bf),mispredicts=Math.round(branches*(1-predAcc)),hazards=Math.round(n*dep*.52),loadUse=Math.round(n*dep*.17),stalls=hazards+loadUse+mispredicts*2,cycles=n+4+stalls,cpi=cycles/n,ipc=n/cycles;return{n,branches,mispredicts,hazards,loadUse,stalls,cycles,cpi,ipc,predAcc}}
function runPipeline(){const r=simulatePipeline();$('#cpi').textContent=r.cpi.toFixed(3);$('#ipc').textContent=r.ipc.toFixed(3);$('#stalls').textContent=fmt(r.stalls);$('#prediction').textContent=(r.predAcc*100).toFixed(1)+'%';$('#heroCpi').textContent=r.cpi.toFixed(2);$('#heroPred').textContent=(r.predAcc*100).toFixed(1)+'%';drawBars($('#pipelineChart'),[{label:'BASE',value:r.n,display:fmt(r.n),color:'#00e5ff'},{label:'CYCLES',value:r.cycles,display:fmt(r.cycles),color:'#9ef01a'},{label:'STALLS',value:r.stalls,display:fmt(r.stalls),color:'#ffc857'},{label:'MISPRED',value:r.mispredicts,display:fmt(r.mispredicts),color:'#ff5d73'}],r.cycles);$('#pipelineTerminal').textContent=`$ archpulse pipeline --instructions ${r.n} --predictor ${$('#predictor').value}\ninstructions=${fmt(r.n)} cycles=${fmt(r.cycles)} CPI=${r.cpi.toFixed(3)} IPC=${r.ipc.toFixed(3)}\nRAW/load hazards=${fmt(r.hazards+r.loadUse)} branch_mispredicts=${fmt(r.mispredicts)} stalls=${fmt(r.stalls)} predictor_accuracy=${(r.predAcc*100).toFixed(1)}%`}
$('#runPipeline').addEventListener('click',runPipeline);
function runScaling(){const f=+$('#parallelFraction').value/100,maxT=+$('#maxThreads').value,threads=[];for(let t=1;t<=maxT;t*=2){const speed=1/((1-f)+f/t);threads.push({xLabel:String(t),y:speed})}if(threads.at(-1).xLabel!==String(maxT)){const t=maxT;threads.push({xLabel:String(t),y:1/((1-f)+f/t)})}const peak=threads.at(-1).y,eff=peak/maxT;$('#peakSpeedup').textContent=peak.toFixed(2)+'×';$('#efficiency').textContent=(eff*100).toFixed(1)+'%';$('#threadMetric').textContent=maxT;$('#serialFloor').textContent=((1-f)*100).toFixed(0)+'%';drawLine($('#scalingChart'),threads,'MODELED SPEEDUP VS THREAD COUNT');$('#scalingTerminal').textContent=`$ archpulse scale --threads ${maxT} --parallel-fraction ${(f*100).toFixed(0)}\nworkload="${$('#workload').value}" modeled_peak_speedup=${peak.toFixed(3)}x efficiency=${(eff*100).toFixed(1)}%\nAnalytical model only — run the C++ benchmark engine for hardware-measured runtime.`}
$('#runScaling').addEventListener('click',runScaling);
window.addEventListener('resize',()=>{runCache();runPipeline();runScaling()});
runCache();runPipeline();runScaling();