#include "archpulse/benchmark.hpp"
#include "archpulse/cache.hpp"
#include "archpulse/metrics.hpp"
#include "archpulse/pipeline.hpp"
#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <iomanip>
#include <iostream>
#include <random>
#include <string>
#include <thread>
#include <vector>
namespace { std::string av(int argc,char**argv,const std::string&k,const std::string&f){for(int i=2;i+1<argc;++i)if(argv[i]==k)return argv[i+1];return f;} std::size_t az(int argc,char**argv,const std::string&k,std::size_t f){return static_cast<std::size_t>(std::stoull(av(argc,argv,k,std::to_string(f))));} void banner(){std::cout<<"\n============================================================\n  ArchPulse - CPU & Compute Performance Workbench\n============================================================\n  Platform: "<<archpulse::platform_name()<<" | Logical CPU threads: "<<std::thread::hardware_concurrency()<<"\n\n";} void usage(){banner();std::cout<<"Usage:\n  archpulse cache [--accesses N] [--cache-size BYTES] [--block-size BYTES] [--ways N] [--pattern mixed|sequential|random] [--csv FILE]\n  archpulse pipeline [--instructions N] [--predictor 2bit|1bit|taken|not-taken] [--csv FILE]\n  archpulse benchmark [--size N] [--threads N] [--workload matrix|convolution] [--csv FILE]\n  archpulse scale [--size N] [--max-threads N] [--csv FILE]\n";} std::vector<std::uint64_t> addresses(std::size_t n,const std::string&p){std::vector<std::uint64_t>a;a.reserve(n);std::mt19937_64 rng(2026);std::uniform_int_distribution<std::uint64_t> wide(0,4*1024*1024),hot(0,64*1024);std::bernoulli_distribution local(.8);for(std::size_t i=0;i<n;++i)a.push_back(p=="sequential"?i*8:p=="random"?wide(rng):(local(rng)?hot(rng):wide(rng)));return a;}
int cache(int argc,char**argv){archpulse::CacheConfig c;c.cache_size_bytes=az(argc,argv,"--cache-size",32768);c.block_size_bytes=az(argc,argv,"--block-size",64);c.ways=az(argc,argv,"--ways",8);auto count=az(argc,argv,"--accesses",100000);auto pattern=av(argc,argv,"--pattern","mixed"),csv=av(argc,argv,"--csv","");archpulse::CacheSimulator sim(c);for(auto x:addresses(count,pattern))sim.access(x);auto&s=sim.stats();std::cout<<"[Cache Simulator]\n  L1: "<<c.cache_size_bytes/1024<<" KiB, "<<c.ways<<"-way, "<<c.block_size_bytes<<" B blocks\n  Accesses: "<<s.accesses<<" | Hits: "<<s.hits<<" | Misses: "<<s.misses<<"\n  Hit rate: "<<std::fixed<<std::setprecision(2)<<s.hit_rate()<<"% | Evictions: "<<s.evictions<<" | Est. cycles: "<<s.estimated_cycles<<"\n\n";if(!csv.empty())archpulse::write_cache_csv(csv,c,s);return 0;}
int pipe(int argc,char**argv){auto n=az(argc,argv,"--instructions",50000);auto k=archpulse::predictor_from_string(av(argc,argv,"--predictor","2bit"));auto csv=av(argc,argv,"--csv","");archpulse::PipelineSimulator sim(k);auto s=sim.run(archpulse::generate_program(n));std::cout<<"[Pipeline Simulator]\n  IF -> ID -> EX -> MEM -> WB | Predictor: "<<archpulse::to_string(k)<<"\n  Instructions: "<<s.instructions<<" | Cycles: "<<s.cycles<<" | CPI: "<<std::fixed<<std::setprecision(3)<<s.cpi()<<" | IPC: "<<s.ipc()<<"\n  Hazards: "<<s.data_hazards<<" | Stalls: "<<s.stalls<<" | Prediction accuracy: "<<std::setprecision(2)<<s.prediction_accuracy()<<"%\n\n";if(!csv.empty())archpulse::write_pipeline_csv(csv,k,s);return 0;}
int bench(int argc,char**argv){auto n=az(argc,argv,"--size",256),t=az(argc,argv,"--threads",std::max(1u,std::thread::hardware_concurrency()));auto w=av(argc,argv,"--workload","matrix"),csv=av(argc,argv,"--csv","");auto r=w=="convolution"?archpulse::benchmark_convolution(n,t):archpulse::benchmark_matrix_multiplication(n,t);std::cout<<"[Parallel Benchmark]\n  Workload: "<<r.workload<<" | Size: "<<r.problem_size<<" | Threads: "<<r.threads<<"\n  Runtime: "<<std::fixed<<std::setprecision(3)<<r.runtime_ms<<" ms | Throughput: "<<r.throughput<<" | Verified: "<<(r.verified?"yes":"no")<<"\n\n";if(!csv.empty())archpulse::write_benchmark_csv(csv,r);return r.verified?0:2;}
int scale(int argc,char**argv){auto n=az(argc,argv,"--size",256),m=az(argc,argv,"--max-threads",std::max(1u,std::thread::hardware_concurrency()));auto csv=av(argc,argv,"--csv","");std::vector<std::size_t>c{1};for(std::size_t t=2;t<=m;t*=2)c.push_back(t);if(c.back()!=m)c.push_back(m);auto rs=archpulse::run_scaling_suite(n,c);std::cout<<"[Scaling Study]\n  Threads   Runtime(ms)   Speedup\n";for(const auto&r:rs){std::cout<<"  "<<std::setw(7)<<r.threads<<"   "<<std::setw(11)<<std::fixed<<std::setprecision(3)<<r.runtime_ms<<"   "<<std::setw(6)<<std::setprecision(2)<<r.speedup<<"x\n";if(!csv.empty())archpulse::write_benchmark_csv(csv,r);}std::cout<<'\n';return 0;}
}
int main(int argc,char**argv){try{if(argc<2||std::string(argv[1])=="--help"){usage();return 0;}banner();std::string c=argv[1];if(c=="cache")return cache(argc,argv);if(c=="pipeline")return pipe(argc,argv);if(c=="benchmark")return bench(argc,argv);if(c=="scale")return scale(argc,argv);usage();return 1;}catch(const std::exception&e){std::cerr<<"ArchPulse error: "<<e.what()<<'\n';return 1;}}
